[package]
name = "sdql"
version = "0.1.0"
edition = "2024"

[lib]
name = "sdql"
path = "src/lib.rs"

[dependencies]
clap = { version = "4.5.28", features = ["derive"] }
csv = "1.3.1" # TODO eventually get rid, it's for runtime
chumsky = { git = "https://github.com/zesterer/chumsky.git", branch = "main" }
derive_more = { version = "2.0.1", features = ["display"] }
im-rc = "15.1.0"
itertools = "0.14.0"
ordered-float = "4.6.0"
prettyplease = "0.2"
proc-macro2 = "1.0"
quote = "1.0"
rayon = "1.10.0" # TODO eventually get rid, it's for runtime
syn = { version = "2.0", features = ["full", "extra-traits"] }
time = { version = "0.3.37", features = ["parsing"] }

sdql_runtime = { path = "runtime" }

[dev-dependencies]
criterion = "0.5.1"

[[bin]]
name = "compile"
path = "src/bin/compile.rs"

[[bench]]
name = "tpch"
harness = false