[package]
name = "sdql"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.1"
hashbrown = { version = "0.15.2", features = ["rayon"] }
itertools = "0.14.0"
ordered-float = "4.6.0"
rayon = "1.10.0"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "tpch"
harness = false
