[package]
name = "sdql"
version = "0.1.0"
edition = "2024"

[lib]
name = "sdql"
path = "src/lib.rs"

[[bin]]
name = "sdql-bin"
path = "src/main.rs"

[dependencies]
csv = "1.3.1"
chumsky = { git = "https://github.com/zesterer/chumsky.git", branch = "main" }
hashbrown = { version = "0.15.2", features = ["rayon"] }
itertools = "0.14.0"
ordered-float = "4.6.0"
rayon = "1.10.0"
quote = "1.0"
syn = { version = "2.0", features = ["full", "extra-traits"] }
proc-macro2 = "1.0"
prettyplease = "0.2"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "tpch"
harness = false
