[package]
name = "sdql"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3.1"
chumsky = { git = "https://github.com/zesterer/chumsky.git", branch = "main" }
hashbrown = { version = "0.15.2", features = ["rayon"] }
ordered-float = "4.6.0"
rayon = "1.10.0"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "tpch"
harness = false
