[package]
name = "sdql"
version = "0.1.0"
edition = "2024"

[lib]
name = "sdql"
path = "src/lib.rs"

[[bin]]
name = "sdql-bin"
path = "src/main.rs"

[dependencies]
arrayvec = "0.7.6"
csv = "1.3.1"
chumsky = { git = "https://github.com/zesterer/chumsky.git", branch = "main" }
derive_more = { version = "2.0.1", features = ["display"] }
hashbrown = { version = "0.15.2", features = ["inline-more", "rayon"] }
im-rc = "15.1.0"
itertools = "0.14.0"
ordered-float = "4.6.0"
rayon = "1.10.0"
quote = "1.0"
syn = { version = "2.0", features = ["full", "extra-traits"] }
proc-macro2 = "1.0"
prettyplease = "0.2"
time = { version = "0.3.37", features = ["formatting", "parsing"] }

wrapped = { path = "wrapped" }

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "tpch"
harness = false
