[project]
name = "plots"
version = "0.1.0"
description = "Plots for thesis"
requires-python = "~=3.13"
dependencies = [
    "black==25.1",
    "matplotlib==3.10",
    "pandas==2.2",
    "seaborn==0.13",
]
